[package]
name = "tokenizers-haskell"
version = "0.1.0"
authors = ["austinvhuang <austinh@alum.mit.edu>"]
edition = "2018"

[lib]
name = "tokenizers_haskell"
crate-type = ["staticlib"]

[dependencies]
tokenizers = { path = "../../tokenizers" }
libc = "0.2"
